name: WordPress Coding Standards Checks

on: push

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: WPCS Check (5.6)
          uses: 10up/wpcs-action@stable
          with:
            excludes: 'Tests'
            enable_warnings: true
            php-version: '5.6'

        - name: WPCS Check (7.4)
          uses: 10up/wpcs-action@stable
          with:
            excludes: 'Tests'
            enable_warnings: true
            php-version: '7.4'

        - name: WPCS Check (8.3)
          uses: 10up/wpcs-action@stable
          with:
            excludes: 'Tests'
            enable_warnings: true
            php-version: '8.3'
